// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo1db3OBj1-ESLfmpnZGbI6zgJT1YyptE',
    appId: '1:246767430236:web:30d3cb95ae44055f6dd499',
    messagingSenderId: '246767430236',
    projectId: 'crypto-mart-53c7b',
    authDomain: 'crypto-mart-53c7b.firebaseapp.com',
    storageBucket: 'crypto-mart-53c7b.firebasestorage.app',
    measurementId: 'G-XVV9H4KZCP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEnCmo6Tb-Urfotvks3vuUc-fV039MQEA',
    appId: '1:246767430236:android:8d9b93d80f1795f86dd499',
    messagingSenderId: '246767430236',
    projectId: 'crypto-mart-53c7b',
    storageBucket: 'crypto-mart-53c7b.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbRJhCCeeEoYv-IfYgYYqoHPwOy6E_F3I',
    appId: '1:246767430236:ios:c9f1d93b0f2aed0c6dd499',
    messagingSenderId: '246767430236',
    projectId: 'crypto-mart-53c7b',
    storageBucket: 'crypto-mart-53c7b.firebasestorage.app',
    iosBundleId: 'com.example.cryptoMart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAo1db3OBj1-ESLfmpnZGbI6zgJT1YyptE',
    appId: '1:246767430236:web:91d15f23f8f309ed6dd499',
    messagingSenderId: '246767430236',
    projectId: 'crypto-mart-53c7b',
    authDomain: 'crypto-mart-53c7b.firebaseapp.com',
    storageBucket: 'crypto-mart-53c7b.firebasestorage.app',
    measurementId: 'G-GZH46Y55RQ',
  );
}
